"use client";

/**
 * Chain API for Paseo Asset Hub Next (v2).
 *
 * Wraps getPaseoAssetHubClient() into the legacy { assetHub, raw } shape used
 * by revive-bulletin-index.ts.
 */

import type { PolkadotClient, TypedApi } from "polkadot-api";
// Local descriptor generated by `npx polkadot-api add paseo_asset_hub -w <ws>`
// against the live chain. The published @parity/product-sdk-descriptors lags
// behind the runtime's signed-extension set (missing EthSetOrigin / AsPgas /
// AsRingAlias / AuthorizeCall as of 2026-06-02) which makes every signed tx
// fail validation with BadProof.
import { paseo_asset_hub } from "@polkadot-api/descriptors";
import { getPaseoAssetHubClient } from "@/lib/host/provider";

interface ChainAPI {
  assetHub: TypedApi<typeof paseo_asset_hub>;
  raw: { assetHub: PolkadotClient };
}

let apiInstance: ChainAPI | null = null;

/**
 * Get the Paseo Asset Hub Next typed API (cached singleton).
 */
export async function getAPI(): Promise<ChainAPI> {
  if (apiInstance) return apiInstance;

  const client = getPaseoAssetHubClient();
  const next: ChainAPI = {
    assetHub: client.getTypedApi(paseo_asset_hub),
    raw: { assetHub: client },
  };
  apiInstance = next;
  return next;
}
